# Generated by Django 3.2.18 on 2023-03-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=11),
        ),
    ]
